/**
 * File: src/const/trails.ts
 * Purpose: Static data for all available walking trails.
 * Created: 2024-01-12
 * Author: AI Assistant
 *
 * Modification History:
 * 2024-01-12: Documentation added.
 */
import { Trail } from '../types';

// Classic Adventures (Americas & Asia) - REMOVED

// Incredible India Treks
export const INDIAN_TRAILS: Trail[] = [
    {
        id: 'roopkund-trek',
        name: 'Roopkund Trek',
        description: 'A trek to the mysterious Skeleton Lake at 16,000 ft in the Himalayas.',
        extendedDescription: 'Famous for the human skeletons found at the edge of the glacial lake, this trek offers a mix of deep virgin forests, gurgling brooks, breath-taking campsites, and miles of undulating meadows (Ali and Bedni Bugyal). The climb to 16,000 ft is challenging but rewarding.',
        totalDistanceMeters: 53000,
        color: '#3B82F6',
        difficulty: 'Hard',
        image: require('../../assets/roopkund_trek.png'),
        startCoordinate: { latitude: 30.26, longitude: 79.73 },
        endCoordinate: { latitude: 30.26, longitude: 79.73 },
        region: {
            latitude: 30.26,
            longitude: 79.73,
            latitudeDelta: 0.1,
            longitudeDelta: 0.1,
        },
        landmarks: [
            { id: 'rk1', name: 'Lohajung', distanceMeters: 0, description: 'Base camp village' },
            { id: 'rk2', name: 'Didna Village', distanceMeters: 8000, description: 'Traditional Himalayan village' },
            { id: 'rk3', name: 'Ali Bugyal', distanceMeters: 18000, description: 'Vast alpine meadows' },
            { id: 'rk3b', name: 'Bedni Bugyal', distanceMeters: 22000, description: 'Camping ground with views' },
            { id: 'rk4', name: 'Ghora Lotani', distanceMeters: 25000, description: 'Scenic campsite' },
            { id: 'rk4b', name: 'Patar Nachauni', distanceMeters: 30000, description: 'Green plateaus' },
            { id: 'rk4c', name: 'Kalu Vinayak', distanceMeters: 33000, description: 'Ganesha temple' },
            { id: 'rk5', name: 'Bhagwabasa', distanceMeters: 35000, description: 'Rocky terrain camp' },
            { id: 'rk6', name: 'Roopkund Lake', distanceMeters: 40000, description: 'The Skeleton Lake' },
            { id: 'rk7', name: 'Junargali', distanceMeters: 41000, description: 'Ridge above the lake' },
            { id: 'rk8', name: 'Wan Village', distanceMeters: 53000, description: 'End of trek' },
        ]
    },
    {
        id: 'chadar-trek',
        name: 'Chadar Trek',
        description: 'The Frozen River Trek on the Zanskar River in Ladakh.',
        extendedDescription: 'One of the most unique treks in the world, walking on the frozen glassy sheet of the Zanskar river. Temperatures drop to -30°C. Experience the dramatic gorge walls and the frozen Nerak waterfall.',
        totalDistanceMeters: 65000,
        color: '#0EA5E9',
        difficulty: 'Extreme',
        image: require('../../assets/chadar_trek.png'),
        startCoordinate: { latitude: 33.77, longitude: 76.84 },
        endCoordinate: { latitude: 33.77, longitude: 76.84 },
        region: {
            latitude: 33.77,
            longitude: 76.84,
            latitudeDelta: 0.2,
            longitudeDelta: 0.2,
        },
        landmarks: [
            { id: 'ct1', name: 'Chilling', distanceMeters: 0, description: 'Start point' },
            { id: 'ct2', name: 'Tilad Sumdo', distanceMeters: 10000, description: 'First camp on ice' },
            { id: 'ct2b', name: 'Shingra Koma', distanceMeters: 20000, description: 'Scenic bend' },
            { id: 'ct3', name: 'Tibb Cave', distanceMeters: 35000, description: 'Natural shelter' },
            { id: 'ct4', name: 'Nerak Waterfall', distanceMeters: 45000, description: 'Iconic frozen waterfall' },
            { id: 'ct5', name: 'Lingshed', distanceMeters: 55000, description: 'Remote village' },
            { id: 'ct6', name: 'Chilling', distanceMeters: 65000, description: 'Return journey' },
        ]
    },
    {
        id: 'kedarkantha-trek',
        name: 'Kedarkantha Trek',
        description: 'Popular winter trek in Uttarakhand with a spectacular summit climb.',
        extendedDescription: 'Perfect for beginners, this trek offers a 360-degree view of famous mountain summits. The trail goes through Govind National Park, offering beautiful campsites like Juda Ka Talab amidst pine forests.',
        totalDistanceMeters: 20000,
        color: '#F59E0B',
        difficulty: 'Moderate',
        image: require('../../assets/kedarkantha_trek.png'),
        startCoordinate: { latitude: 31.02, longitude: 78.17 },
        endCoordinate: { latitude: 31.02, longitude: 78.17 },
        region: {
            latitude: 31.02,
            longitude: 78.17,
            latitudeDelta: 0.05,
            longitudeDelta: 0.05,
        },
        landmarks: [
            { id: 'kt1', name: 'Sankri', distanceMeters: 0, description: 'Base village' },
            { id: 'kt2', name: 'Juda Ka Talab', distanceMeters: 4000, description: 'Frozen lake campsite' },
            { id: 'kt3', name: 'Base Camp', distanceMeters: 8000, description: 'Below the summit' },
            { id: 'kt4', name: 'Kedarkantha Summit', distanceMeters: 10000, description: '3800m Peak' },
            { id: 'kt5', name: 'Hargaon', distanceMeters: 15000, description: 'Descent camp' },
            { id: 'kt6', name: 'Sankri', distanceMeters: 20000, description: 'Trek complete' },
        ]
    },
    {
        id: 'valley-of-flowers',
        name: 'Valley of Flowers',
        description: 'A UNESCO World Heritage site known for its endless meadows of alpine flowers.',
        extendedDescription: 'Legendary trek in global trekking circles. Visit during monsoon to see the valley carpeted with flowers like the Blue Poppy and Cobra Lily. Nearby is the Hemkund Sahib Gurudwara.',
        totalDistanceMeters: 38000,
        color: '#EC4899',
        difficulty: 'Moderate',
        image: require('../../assets/valley_of_flowers.png'),
        startCoordinate: { latitude: 30.73, longitude: 79.63 },
        endCoordinate: { latitude: 30.73, longitude: 79.63 },
        region: {
            latitude: 30.73,
            longitude: 79.63,
            latitudeDelta: 0.1,
            longitudeDelta: 0.1,
        },
        landmarks: [
            { id: 'vof1', name: 'Govindghat', distanceMeters: 0, description: 'Start of the trail' },
            { id: 'vof2', name: 'Ghangaria', distanceMeters: 14000, description: 'Base for the valley' },
            { id: 'vof3', name: 'Valley Entry', distanceMeters: 18000, description: 'Entrance to the park' },
            { id: 'vof4', name: 'Tipra Glacier', distanceMeters: 24000, description: 'End of the valley trail' },
            { id: 'vof5', name: 'Hemkund Sahib', distanceMeters: 30000, description: 'Optional spiritual climb' },
            { id: 'vof6', name: 'Govindghat', distanceMeters: 38000, description: 'Return journey' },
        ]
    },
    {
        id: 'hampta-pass',
        name: 'Hampta Pass Trek',
        description: 'Dramatic crossover trek from lush Kullu valley to arid Spiti valley.',
        extendedDescription: 'A trek of stark contrasts. Start in the green pine forests of Manali and cross the 14,000 ft pass to enter the barren, rugged landscape of Lahaul. Visit the stunning Chandratal lake.',
        totalDistanceMeters: 26000,
        color: '#10B981',
        difficulty: 'Moderate',
        image: require('../../assets/hampta_pass.png'),
        startCoordinate: { latitude: 32.24, longitude: 77.37 },
        endCoordinate: { latitude: 32.24, longitude: 77.37 },
        region: {
            latitude: 32.24,
            longitude: 77.37,
            latitudeDelta: 0.2,
            longitudeDelta: 0.2,
        },
        landmarks: [
            { id: 'hp1', name: 'Jobra', distanceMeters: 0, description: 'Trailhead' },
            { id: 'hp2', name: 'Chika', distanceMeters: 4000, description: 'River campsite' },
            { id: 'hp3', name: 'Balu Ka Ghera', distanceMeters: 12000, description: 'Base of the pass' },
            { id: 'hp4', name: 'Hampta Pass', distanceMeters: 16000, description: 'The crossover point' },
            { id: 'hp5', name: 'Shea Goru', distanceMeters: 20000, description: 'Descent campsite' },
            { id: 'hp6', name: 'Chatru', distanceMeters: 26000, description: 'End point' },
        ]
    },
    {
        id: 'goechala-trek',
        name: 'Goechala Trek',
        description: 'Close-up views of the majestic Kanchenjunga peak in Sikkim.',
        extendedDescription: 'Offers grand views of big mountains. You see 14 big summits. The sunrise on the Kanchenjunga range is legendary. Trail passes through beautiful rhododendron forests of Dzongri.',
        totalDistanceMeters: 90000,
        color: '#8B5CF6',
        difficulty: 'Hard',
        image: require('../../assets/goechala_trek.png'),
        startCoordinate: { latitude: 27.57, longitude: 88.19 },
        endCoordinate: { latitude: 27.57, longitude: 88.19 },
        region: {
            latitude: 27.57,
            longitude: 88.19,
            latitudeDelta: 0.1,
            longitudeDelta: 0.1,
        },
        landmarks: [
            { id: 'gt1', name: 'Yuksom', distanceMeters: 0, description: 'Historical base' },
            { id: 'gt2', name: 'Sachen', distanceMeters: 8000, description: 'Forest walk' },
            { id: 'gt2b', name: 'Bakhim', distanceMeters: 12000, description: 'Steep ascent' },
            { id: 'gt3', name: 'Tshoka', distanceMeters: 16000, description: 'Tibetan settlement' },
            { id: 'gt3b', name: 'Phedang', distanceMeters: 21000, description: 'Forest clearing' },
            { id: 'gt4', name: 'Dzongri', distanceMeters: 25000, description: 'Viewpoint' },
            { id: 'gt4b', name: 'Dzongri Top', distanceMeters: 27000, description: 'Sunrise view' },
            { id: 'gt5', name: 'Thansing', distanceMeters: 35000, description: 'Meadows' },
            { id: 'gt5b', name: 'Lamuney', distanceMeters: 40000, description: 'Base camp' },
            { id: 'gt6', name: 'Goechala Viewpoint', distanceMeters: 45000, description: 'Kanchenjunga face-to-face' },
            { id: 'gt7', name: 'Yuksom', distanceMeters: 90000, description: 'Return journey' },
        ]
    },
    {
        id: 'markha-valley',
        name: 'Markha Valley Trek',
        description: 'A dive into Ladakhi culture and arid landscapes in Hemis National Park.',
        extendedDescription: 'Walk through "Little Tibet". Dry mountains, streams, and barley fields. Homestays in remote villages are a highlight. Cross the Kongmaru La pass at 17,000 ft.',
        totalDistanceMeters: 78000,
        color: '#D946EF',
        difficulty: 'Hard',
        image: require('../../assets/markha_valley.png'),
        startCoordinate: { latitude: 33.91, longitude: 77.34 },
        endCoordinate: { latitude: 33.91, longitude: 77.34 },
        region: {
            latitude: 33.91,
            longitude: 77.34,
            latitudeDelta: 0.3,
            longitudeDelta: 0.3,
        },
        landmarks: [
            { id: 'mv1', name: 'Chilling', distanceMeters: 0, description: 'Start' },
            { id: 'mv2', name: 'Skiu', distanceMeters: 15000, description: 'First village' },
            { id: 'mv2b', name: 'Sara', distanceMeters: 25000, description: 'River camp' },
            { id: 'mv3', name: 'Markha', distanceMeters: 40000, description: 'Major village' },
            { id: 'mv3b', name: 'Hankar', distanceMeters: 50000, description: 'Village with fort' },
            { id: 'mv4', name: 'Nimaling', distanceMeters: 60000, description: 'High plains' },
            { id: 'mv5', name: 'Kongmaru La', distanceMeters: 65000, description: 'High pass (5200m)' },
            { id: 'mv6', name: 'Shang Sumdo', distanceMeters: 78000, description: 'End point' },
        ]
    },
    {
        id: 'stok-kangri',
        name: 'Stok Kangri Trek',
        description: 'A serious expedition to climb a 6,153m trek-able summit in Ladakh.',
        extendedDescription: 'Often considered the highest trek-able summit in India. Requires acclimatization and physical fitness. The view from the top includes the Karakoram range and K2 on a clear day.',
        totalDistanceMeters: 40000,
        color: '#6366F1',
        difficulty: 'Extreme',
        image: require('../../assets/stok_kangri.png'),
        startCoordinate: { latitude: 33.98, longitude: 77.44 },
        endCoordinate: { latitude: 33.98, longitude: 77.44 },
        region: {
            latitude: 33.98,
            longitude: 77.44,
            latitudeDelta: 0.1,
            longitudeDelta: 0.1,
        },
        landmarks: [
            { id: 'sk1', name: 'Stok Village', distanceMeters: 0, description: 'Start' },
            { id: 'sk2', name: 'Chang Ma', distanceMeters: 6000, description: 'First camp' },
            { id: 'sk3', name: 'Mankorma', distanceMeters: 10000, description: 'Acclimatization' },
            { id: 'sk4', name: 'Base Camp', distanceMeters: 15000, description: 'Below the peak' },
            { id: 'sk5', name: 'Summit', distanceMeters: 20000, description: '6153m Top' },
            { id: 'sk6', name: 'Stok Village', distanceMeters: 40000, description: 'Return' },
        ]
    },
    {
        id: 'kumara_parvatha',
        name: 'Kumara Parvatha Trek',
        description: 'The toughest trek in Karnataka, offering varied terrain in the Western Ghats.',
        extendedDescription: 'A classic trek in the verdant Western Ghats. Passes through ancient forests, grasslands, and rocky faces. The Bhattara Mane is a famous pitstop. The peak offers views of Coorg landscapes.',
        totalDistanceMeters: 25000,
        color: '#22C55E',
        difficulty: 'Hard',
        image: require('../../assets/kumara_parvatha.png'),
        startCoordinate: { latitude: 12.66, longitude: 75.68 },
        endCoordinate: { latitude: 12.66, longitude: 75.68 },
        region: {
            latitude: 12.66,
            longitude: 75.68,
            latitudeDelta: 0.05,
            longitudeDelta: 0.05,
        },
        landmarks: [
            { id: 'kp1', name: 'Kukke Temple', distanceMeters: 0, description: 'Start' },
            { id: 'kp2', name: 'Bhattara Mane', distanceMeters: 6000, description: 'Forest house' },
            { id: 'kp3', name: 'Kallu Mantapa', distanceMeters: 9000, description: 'Stone shelter' },
            { id: 'kp4', name: 'Shesha Parvatha', distanceMeters: 11000, description: 'False peak' },
            { id: 'kp5', name: 'Kumara Parvatha', distanceMeters: 13000, description: 'Summit' },
            { id: 'kp6', name: 'Kukke', distanceMeters: 25000, description: 'Back to base' },
        ]
    },
    {
        id: 'mullayanagiri-trek',
        name: 'Mullayanagiri Trek',
        description: 'Trek to the highest peak in Karnataka.',
        extendedDescription: 'A pleasant trek in the coffee district of Chikmagalur. The trail is often misty and windy. At the top, there is a small temple dedicated to Mullappa Swamy. Great for beginners.',
        totalDistanceMeters: 6000,
        color: '#14B8A6',
        difficulty: 'Easy',
        image: require('../../assets/mullayanagiri.png'),
        startCoordinate: { latitude: 13.39, longitude: 75.72 },
        endCoordinate: { latitude: 13.39, longitude: 75.72 },
        region: {
            latitude: 13.39,
            longitude: 75.72,
            latitudeDelta: 0.02,
            longitudeDelta: 0.02,
        },
        landmarks: [
            { id: 'mg1', name: 'Sarpadhari', distanceMeters: 0, description: 'Trailhead' },
            { id: 'mg2', name: 'Nandi Statue', distanceMeters: 1500, description: 'Landmark' },
            { id: 'mg3', name: 'Cave', distanceMeters: 2500, description: 'Caves' },
            { id: 'mg4', name: 'Summit', distanceMeters: 3000, description: 'Temple at top' },
            { id: 'mg5', name: 'Sarpadhari', distanceMeters: 6000, description: 'Descend' },
        ]
    },
    {
        id: 'chembra-peak',
        name: 'Chembra Peak Trek',
        description: 'Known for its heart-shaped lake in Wayanad, Kerala.',
        extendedDescription: 'A scenic hike through tea gardens and forests. The main attraction is the Hridaya Saras, a heart-shaped lake that is believed to never dry up. Offers views of the Nilgiris.',
        totalDistanceMeters: 9000,
        color: '#84CC16',
        difficulty: 'Moderate',
        image: require('../../assets/chembra_peak.png'),
        startCoordinate: { latitude: 11.51, longitude: 76.09 },
        endCoordinate: { latitude: 11.51, longitude: 76.09 },
        region: {
            latitude: 11.51,
            longitude: 76.09,
            latitudeDelta: 0.05,
            longitudeDelta: 0.05,
        },
        landmarks: [
            { id: 'cp1', name: 'Forest Office', distanceMeters: 0, description: 'Checkpost' },
            { id: 'cp2', name: 'Watchtower', distanceMeters: 2000, description: 'Viewpoint' },
            { id: 'cp3', name: 'Heart Lake', distanceMeters: 4500, description: 'Hridaya Saras' },
            { id: 'cp4', name: 'Forest Office', distanceMeters: 9000, description: 'Return' },
        ]
    },
    {
        id: 'rajmachi-trek',
        name: 'Rajmachi Trek',
        description: 'A historical fort trek in the Sahyadris, beautiful in monsoons.',
        extendedDescription: 'A favorite among monsoon trekkers. Famous for fireflies in pre-monsoon. The twin forts of Shrivardhan and Manaranjan offer great views. Can be started from Lonavala or Karjat.',
        totalDistanceMeters: 16000,
        color: '#F43F5E',
        difficulty: 'Easy',
        image: require('../../assets/rajmachi.png'),
        startCoordinate: { latitude: 18.82, longitude: 73.39 },
        endCoordinate: { latitude: 18.82, longitude: 73.39 },
        region: {
            latitude: 18.82,
            longitude: 73.39,
            latitudeDelta: 0.1,
            longitudeDelta: 0.1,
        },
        landmarks: [
            { id: 'rm1', name: 'Udhewadi', distanceMeters: 0, description: 'Base village' },
            { id: 'rm2', name: 'Shrivardhan', distanceMeters: 4000, description: 'Higher fort' },
            { id: 'rm3', name: 'Manaranjan', distanceMeters: 8000, description: 'Lower fort' },
            { id: 'rm4', name: 'Kondhane Caves', distanceMeters: 12000, description: 'Ancient caves' },
            { id: 'rm5', name: 'Kondhane', distanceMeters: 16000, description: 'End point' },
        ]
    },
    {
        id: 'dzukou-valley',
        name: 'Dzükou Valley Trek',
        description: 'The valley of flowers in Northeast India, Nagaland.',
        extendedDescription: 'A hidden gem on the Nagaland-Manipur border. Famous for the endemic Dzukou Lily and rolling emerald green hills. The landscape is unique, unlike anywhere else in India.',
        totalDistanceMeters: 20000,
        color: '#06B6D4',
        difficulty: 'Moderate',
        image: require('../../assets/dzukou_valley.png'),
        startCoordinate: { latitude: 25.55, longitude: 94.07 },
        endCoordinate: { latitude: 25.55, longitude: 94.07 },
        region: {
            latitude: 25.55,
            longitude: 94.07,
            latitudeDelta: 0.05,
            longitudeDelta: 0.05,
        },
        landmarks: [
            { id: 'dv1', name: 'Viswema', distanceMeters: 0, description: 'Starting point' },
            { id: 'dv2', name: 'Rest Point', distanceMeters: 5000, description: 'Midway' },
            { id: 'dv3', name: 'Guest House', distanceMeters: 10000, description: 'Valley view' },
            { id: 'dv4', name: 'Valley Bottom', distanceMeters: 12000, description: 'Explore' },
            { id: 'dv5', name: 'Viswema', distanceMeters: 20000, description: 'Return' },
        ]
    },
    {
        id: 'sandakphu-trek',
        name: 'Sandakphu Trek',
        description: 'West Bengal\'s highest peak offering views of 4 of the world\'s highest mountains.',
        extendedDescription: 'A classic ridge trek along the Indo-Nepal border. On a clear day, see Everest, Kanchenjunga, Lhotse, and Makalu. Visit various villages and experience the culture.',
        totalDistanceMeters: 45000,
        color: '#F97316',
        difficulty: 'Moderate',
        image: require('../../assets/sandakphu.png'),
        startCoordinate: { latitude: 27.10, longitude: 88.00 },
        endCoordinate: { latitude: 27.10, longitude: 88.00 },
        region: {
            latitude: 27.10,
            longitude: 88.00,
            latitudeDelta: 0.1,
            longitudeDelta: 0.1,
        },
        landmarks: [
            { id: 'sp1', name: 'Manebhanjan', distanceMeters: 0, description: 'Start' },
            { id: 'sp2', name: 'Tumling', distanceMeters: 11000, description: 'Nepal border' },
            { id: 'sp3', name: 'Kalipokhari', distanceMeters: 26000, description: 'Black pond' },
            { id: 'sp4', name: 'Sandakphu', distanceMeters: 32000, description: 'Summit View' },
            { id: 'sp5', name: 'Srikhola', distanceMeters: 45000, description: 'End point' },
        ]
    },
    {
        id: 'harishchandragad-trek',
        name: 'Harishchandragad Trek',
        description: 'Famous for the Konkan Kada cliff and ancient temples.',
        extendedDescription: 'A hill fort in Ahmednagar district. The Konkan Kada is a massive cliff with a concave shape. The Kedareshwar Cave has a big Shiva Linga surrounded by water.',
        totalDistanceMeters: 12000,
        color: '#A855F7',
        difficulty: 'Moderate',
        image: require('../../assets/harishchandragad.png'),
        startCoordinate: { latitude: 19.38, longitude: 73.77 },
        endCoordinate: { latitude: 19.38, longitude: 73.77 },
        region: {
            latitude: 19.38,
            longitude: 73.77,
            latitudeDelta: 0.05,
            longitudeDelta: 0.05,
        },
        landmarks: [
            { id: 'hc1', name: 'Pachnai', distanceMeters: 0, description: 'Base village' },
            { id: 'hc2', name: 'Harishchandreshwar', distanceMeters: 3000, description: 'Temple' },
            { id: 'hc3', name: 'Konkan Kada', distanceMeters: 4000, description: 'Major cliff' },
            { id: 'hc4', name: 'Taramati Peak', distanceMeters: 6000, description: 'Highest point' },
            { id: 'hc5', name: 'Pachnai', distanceMeters: 12000, description: 'Return' },
        ]
    }
];

// Classic Distance Marathons
export const CLASSIC_MARATHONS: Trail[] = [
    {
        id: '5k-challenge',
        name: '5K Challenge',
        description: 'A perfect beginner distance to start your marathon journey.',
        extendedDescription: 'The 5K is the most accessible marathon distance, perfect for beginners or those looking for a quick, energizing workout. Complete this distance to build confidence and momentum.',
        totalDistanceMeters: 5000,
        color: '#22C55E',
        difficulty: 'Easy',
        image: require('../../assets/5k_marathon.png'),
        startCoordinate: { latitude: 0, longitude: 0 },
        endCoordinate: { latitude: 0, longitude: 0 },
        region: { latitude: 0, longitude: 0, latitudeDelta: 0.1, longitudeDelta: 0.1 },
        landmarks: [
            { id: '5k-1', name: 'Starting Line', distanceMeters: 0, description: 'Begin your journey!' },
            { id: '5k-2', name: 'Quarter Mark', distanceMeters: 1250, description: '25% Complete - Finding your rhythm' },
            { id: '5k-3', name: 'Halfway Point', distanceMeters: 2500, description: '50% Complete - You\'re doing great!' },
            { id: '5k-4', name: 'Three Quarter Mark', distanceMeters: 3750, description: '75% Complete - Almost there!' },
            { id: '5k-5', name: 'Finish Line', distanceMeters: 5000, description: '5K Completed! Well done!' },
        ]
    },
    {
        id: '10k-classic',
        name: '10K Classic',
        description: 'The perfect balance of challenge and achievability.',
        extendedDescription: 'The 10K is one of the most popular running distances worldwide. It\'s long enough to be challenging but short enough to be achievable with regular training. Perfect for intermediate walkers.',
        totalDistanceMeters: 10000,
        color: '#3B82F6',
        difficulty: 'Moderate',
        image: require('../../assets/10k_marathon.png'),
        startCoordinate: { latitude: 0, longitude: 0 },
        endCoordinate: { latitude: 0, longitude: 0 },
        region: { latitude: 0, longitude: 0, latitudeDelta: 0.1, longitudeDelta: 0.1 },
        landmarks: [
            { id: '10k-1', name: 'Starting Line', distanceMeters: 0, description: 'Let\'s go!' },
            { id: '10k-2', name: 'Quarter Mark', distanceMeters: 2500, description: '25% Complete - Strong start!' },
            { id: '10k-3', name: 'Halfway Point', distanceMeters: 5000, description: '50% Complete - Keep the pace!' },
            { id: '10k-4', name: 'Three Quarter Mark', distanceMeters: 7500, description: '75% Complete - Final push!' },
            { id: '10k-5', name: 'Finish Line', distanceMeters: 10000, description: '10K Completed! Excellent!' },
        ]
    },
    {
        id: 'half-marathon',
        name: 'Half Marathon',
        description: 'The classic 21.1km challenge - a true test of endurance.',
        extendedDescription: 'The half marathon is a significant achievement that requires dedication and training. At 21.1km, it\'s exactly half the distance of a full marathon and a popular goal for serious recreational runners.',
        totalDistanceMeters: 21100,
        color: '#F59E0B',
        difficulty: 'Hard',
        image: require('../../assets/half_marathon.png'),
        startCoordinate: { latitude: 0, longitude: 0 },
        endCoordinate: { latitude: 0, longitude: 0 },
        region: { latitude: 0, longitude: 0, latitudeDelta: 0.1, longitudeDelta: 0.1 },
        landmarks: [
            { id: 'half-1', name: 'Starting Line', distanceMeters: 0, description: 'The journey begins!' },
            { id: 'half-2', name: 'Quarter Mark', distanceMeters: 5275, description: '25% Complete - Feeling good!' },
            { id: 'half-3', name: 'Halfway Point', distanceMeters: 10550, description: '50% Complete - Halfway home!' },
            { id: 'half-4', name: 'Three Quarter Mark', distanceMeters: 15825, description: '75% Complete - Dig deep!' },
            { id: 'half-5', name: 'Finish Line', distanceMeters: 21100, description: 'Half Marathon Complete! Amazing!' },
        ]
    },
    {
        id: 'full-marathon',
        name: 'Full Marathon',
        description: 'The legendary 42.2km - the ultimate endurance challenge.',
        extendedDescription: 'The marathon is the crown jewel of long-distance running. At 42.195km, it commemorates the legendary run of Pheidippides from Marathon to Athens. Completing a marathon is a life-changing achievement.',
        totalDistanceMeters: 42195,
        color: '#EF4444',
        difficulty: 'Extreme',
        image: require('../../assets/full_marathon.png'),
        startCoordinate: { latitude: 0, longitude: 0 },
        endCoordinate: { latitude: 0, longitude: 0 },
        region: { latitude: 0, longitude: 0, latitudeDelta: 0.1, longitudeDelta: 0.1 },
        landmarks: [
            { id: 'full-1', name: 'Starting Line', distanceMeters: 0, description: 'The ultimate challenge begins!' },
            { id: 'full-2', name: 'Quarter Mark', distanceMeters: 10549, description: '25% Complete - Feeling strong!' },
            { id: 'full-3', name: 'Halfway Point', distanceMeters: 21098, description: '50% Complete - You\'re unstoppable!' },
            { id: 'full-4', name: 'Three Quarter Mark', distanceMeters: 31646, description: '75% Complete - Legendary effort!' },
            { id: 'full-5', name: 'Finish Line', distanceMeters: 42195, description: 'Marathon Complete! You\'re a champion!' },
        ]
    },
    {
        id: 'ultra-50',
        name: 'Ultra 50',
        description: 'Enter ultra territory with a 50km challenge.',
        extendedDescription: 'The 50km ultra marathon takes you beyond the traditional marathon distance. This is where true endurance athletes test their limits. Requires serious training and mental fortitude.',
        totalDistanceMeters: 50000,
        color: '#8B5CF6',
        difficulty: 'Extreme',
        image: require('../../assets/ultra_50.png'),
        startCoordinate: { latitude: 0, longitude: 0 },
        endCoordinate: { latitude: 0, longitude: 0 },
        region: { latitude: 0, longitude: 0, latitudeDelta: 0.1, longitudeDelta: 0.1 },
        landmarks: [
            { id: 'u50-1', name: 'Starting Line', distanceMeters: 0, description: 'Ultra journey begins!' },
            { id: 'u50-2', name: 'Quarter Mark', distanceMeters: 12500, description: '25% Complete - Going ultra!' },
            { id: 'u50-3', name: 'Halfway Point', distanceMeters: 25000, description: '50% Complete - Beyond limits!' },
            { id: 'u50-4', name: 'Three Quarter Mark', distanceMeters: 37500, description: '75% Complete - Incredible determination!' },
            { id: 'u50-5', name: 'Finish Line', distanceMeters: 50000, description: 'Ultra 50 Complete! Extraordinary!' },
        ]
    },
    {
        id: 'ultra-100',
        name: 'Ultra 100',
        description: 'The ultimate ultra marathon - a legendary 100km journey.',
        extendedDescription: 'The 100km ultra marathon is reserved for the most dedicated endurance athletes. This distance pushes you to discover what you\'re truly capable of. Only the most determined complete this journey.',
        totalDistanceMeters: 100000,
        color: '#DC2626',
        difficulty: 'Extreme',
        image: require('../../assets/ultra_100.png'),
        startCoordinate: { latitude: 0, longitude: 0 },
        endCoordinate: { latitude: 0, longitude: 0 },
        region: { latitude: 0, longitude: 0, latitudeDelta: 0.1, longitudeDelta: 0.1 },
        landmarks: [
            { id: 'u100-1', name: 'Starting Line', distanceMeters: 0, description: 'Epic journey begins!' },
            { id: 'u100-2', name: 'Quarter Mark', distanceMeters: 25000, description: '25% Complete - Relentless!' },
            { id: 'u100-3', name: 'Halfway Point', distanceMeters: 50000, description: '50% Complete - Unstoppable force!' },
            { id: 'u100-4', name: 'Three Quarter Mark', distanceMeters: 75000, description: '75% Complete - Legendary status!' },
            { id: 'u100-5', name: 'Finish Line', distanceMeters: 100000, description: 'Ultra 100 Complete! You\'re a legend!' },
        ]
    },
];

// City Marathons - Famous Routes
export const CITY_MARATHONS: Trail[] = [
    {
        id: 'mumbai-marathon',
        name: 'Mumbai Marathon',
        description: 'India\'s most prestigious marathon through the city of dreams.',
        extendedDescription: 'Run through the heart of Mumbai, from Chhatrapati Shivaji Terminus to the iconic Marine Drive. Experience the energy of India\'s financial capital as you pass landmarks that define this vibrant metropolis.',
        totalDistanceMeters: 42195,
        color: '#FF6B35',
        difficulty: 'Hard',
        image: require('../../assets/mumbai_marathon.png'),
        startCoordinate: { latitude: 18.9398, longitude: 72.8355 },
        endCoordinate: { latitude: 18.9220, longitude: 72.8231 },
        region: { latitude: 18.9300, longitude: 72.8300, latitudeDelta: 0.1, longitudeDelta: 0.1 },
        landmarks: [
            { id: 'mum-1', name: 'CST Starting Point', distanceMeters: 0, description: 'UNESCO World Heritage terminus' },
            { id: 'mum-2', name: 'Gateway of India', distanceMeters: 3500, description: 'Iconic monument by the sea' },
            { id: 'mum-3', name: 'Nariman Point', distanceMeters: 8000, description: 'Business district skyline' },
            { id: 'mum-4', name: 'Worli Sea Link', distanceMeters: 15000, description: 'Engineering marvel over the sea' },
            { id: 'mum-5', name: 'Bandra-Worli Junction', distanceMeters: 21098, description: 'Halfway through the city' },
            { id: 'mum-6', name: 'Mahim Causeway', distanceMeters: 28000, description: 'Historic connector' },
            { id: 'mum-7', name: 'Dadar Circle', distanceMeters: 33000, description: 'Heart of Mumbai' },
            { id: 'mum-8', name: 'Chowpatty Beach', distanceMeters: 38000, description: 'Famous seafront' },
            { id: 'mum-9', name: 'Marine Drive', distanceMeters: 42195, description: 'Queen\'s Necklace finish!' },
        ]
    },
    {
        id: 'new-york-marathon',
        name: 'New York City Marathon',
        description: 'Run through all five boroughs of the Big Apple.',
        extendedDescription: 'The world\'s largest marathon takes you from Staten Island through Brooklyn, Queens, the Bronx, and finishes in Manhattan\'s Central Park. Experience the unmatched energy of millions of cheering spectators.',
        totalDistanceMeters: 42195,
        color: '#1E40AF',
        difficulty: 'Hard',
        image: require('../../assets/new_york_marathon.png'),
        startCoordinate: { latitude: 40.6093, longitude: -74.0555 },
        endCoordinate: { latitude: 40.7689, longitude: -73.9831 },
        region: { latitude: 40.7128, longitude: -74.0060, latitudeDelta: 0.3, longitudeDelta: 0.3 },
        landmarks: [
            { id: 'nyc-1', name: 'Staten Island Start', distanceMeters: 0, description: 'Verrazano-Narrows Bridge' },
            { id: 'nyc-2', name: 'Brooklyn Heights', distanceMeters: 6000, description: 'Historic neighborhood' },
            { id: 'nyc-3', name: 'Williamsburg', distanceMeters: 12000, description: 'Hipster haven' },
            { id: 'nyc-4', name: 'Queensboro Bridge', distanceMeters: 21098, description: 'Halfway - iconic bridge' },
            { id: 'nyc-5', name: 'First Avenue', distanceMeters: 26000, description: 'Manhattan energy' },
            { id: 'nyc-6', name: 'The Bronx', distanceMeters: 32000, description: 'Only mainland borough' },
            { id: 'nyc-7', name: 'Fifth Avenue', distanceMeters: 37000, description: 'Luxury mile' },
            { id: 'nyc-8', name: 'Central Park South', distanceMeters: 40000, description: 'Almost there!' },
            { id: 'nyc-9', name: 'Central Park Finish', distanceMeters: 42195, description: 'New York Marathon complete!' },
        ]
    },
    {
        id: 'london-marathon',
        name: 'London Marathon',
        description: 'A royal route through Britain\'s capital city.',
        extendedDescription: 'Run past some of London\'s most famous landmarks including Tower Bridge, Big Ben, and Buckingham Palace. Finish on The Mall with thousands cheering you on. One of the World Marathon Majors.',
        totalDistanceMeters: 42195,
        color: '#991B1B',
        difficulty: 'Hard',
        image: require('../../assets/london_marathon.png'),
        startCoordinate: { latitude: 51.4669, longitude: 0.0090 },
        endCoordinate: { latitude: 51.5074, longitude: -0.1278 },
        region: { latitude: 51.5074, longitude: -0.1278, latitudeDelta: 0.15, longitudeDelta: 0.15 },
        landmarks: [
            { id: 'ldn-1', name: 'Greenwich Park Start', distanceMeters: 0, description: 'Historic royal park' },
            { id: 'ldn-2', name: 'Cutty Sark', distanceMeters: 3000, description: 'Historic clipper ship' },
            { id: 'ldn-3', name: 'Tower Bridge', distanceMeters: 12000, description: 'London\'s iconic bridge' },
            { id: 'ldn-4', name: 'Canary Wharf', distanceMeters: 18000, description: 'Financial district' },
            { id: 'ldn-5', name: 'Isle of Dogs', distanceMeters: 21098, description: 'Halfway point' },
            { id: 'ldn-6', name: 'The Highway', distanceMeters: 26000, description: 'Historic East End' },
            { id: 'ldn-7', name: 'The Embankment', distanceMeters: 35000, description: 'Along the Thames' },
            { id: 'ldn-8', name: 'Big Ben', distanceMeters: 40000, description: 'Parliament\'s tower' },
            { id: 'ldn-9', name: 'The Mall Finish', distanceMeters: 42195, description: 'Buckingham Palace view!' },
        ]
    },
    {
        id: 'tokyo-marathon',
        name: 'Tokyo Marathon',
        description: 'Experience Japan\'s blend of tradition and modernity.',
        extendedDescription: 'Run through Tokyo\'s most vibrant districts from Shinjuku to Tokyo Station. Pass temples, skyscrapers, and the Imperial Palace. Experience unmatched organization and enthusiastic support from Japanese spectators.',
        totalDistanceMeters: 42195,
        color: '#DC2626',
        difficulty: 'Hard',
        image: require('../../assets/tokyo_marathon.png'),
        startCoordinate: { latitude: 35.6895, longitude: 139.6917 },
        endCoordinate: { latitude: 35.6812, longitude: 139.7671 },
        region: { latitude: 35.6762, longitude: 139.6503, latitudeDelta: 0.15, longitudeDelta: 0.15 },
        landmarks: [
            { id: 'tky-1', name: 'Tokyo Metropolitan Government', distanceMeters: 0, description: 'Shinjuku start' },
            { id: 'tky-2', name: 'Iidabashi', distanceMeters: 5000, description: 'Historic district' },
            { id: 'tky-3', name: 'Imperial Palace', distanceMeters: 10000, description: 'Emperor\'s residence' },
            { id: 'tky-4', name: 'Nihonbashi', distanceMeters: 15000, description: 'Historic bridge' },
            { id: 'tky-5', name: 'Asakusa', distanceMeters: 21098, description: 'Senso-ji Temple area' },
            { id: 'tky-6', name: 'Kanda', distanceMeters: 28000, description: 'Electronics district' },
            { id: 'tky-7', name: 'Ginza', distanceMeters: 34000, description: 'Luxury shopping' },
            { id: 'tky-8', name: 'Tsukiji', distanceMeters: 39000, description: 'Fish market area' },
            { id: 'tky-9', name: 'Tokyo Station', distanceMeters: 42195, description: 'Majestic finish!' },
        ]
    },
    {
        id: 'boston-marathon',
        name: 'Boston Marathon',
        description: 'The world\'s oldest annual marathon since 1897.',
        extendedDescription: 'Run from Hopkinton to Boston on Patriots\' Day. Conquer the legendary Heartbreak Hill and finish on Boylston Street. Qualifying times required - this is for serious marathoners only.',
        totalDistanceMeters: 42195,
        color: '#1E3A8A',
        difficulty: 'Extreme',
        image: require('../../assets/boston_marathon.png'),
        startCoordinate: { latitude: 42.2279, longitude: -71.5165 },
        endCoordinate: { latitude: 42.3495, longitude: -71.0793 },
        region: { latitude: 42.2887, longitude: -71.2979, latitudeDelta: 0.3, longitudeDelta: 0.3 },
        landmarks: [
            { id: 'bos-1', name: 'Hopkinton Start', distanceMeters: 0, description: 'Historic starting line' },
            { id: 'bos-2', name: 'Ashland', distanceMeters: 6000, description: 'First town' },
            { id: 'bos-3', name: 'Framingham', distanceMeters: 11000, description: 'Scream Tunnel ahead' },
            { id: 'bos-4', name: 'Wellesley College', distanceMeters: 21098, description: 'Halfway - Scream Tunnel!' },
            { id: 'bos-5', name: 'Newton Hills Start', distanceMeters: 27000, description: 'The hills begin' },
            { id: 'bos-6', name: 'Heartbreak Hill', distanceMeters: 33000, description: 'Legendary climb' },
            { id: 'bos-7', name: 'Boston College', distanceMeters: 34500, description: 'Summit conquered!' },
            { id: 'bos-8', name: 'Kenmore Square', distanceMeters: 40000, description: 'Final stretch' },
            { id: 'bos-9', name: 'Boylston Street', distanceMeters: 42195, description: 'Historic finish line!' },
        ]
    },
    {
        id: 'berlin-marathon',
        name: 'Berlin Marathon',
        description: 'The world\'s fastest marathon course.',
        extendedDescription: 'Run through reunified Berlin on the flattest, fastest course in the world. Multiple world records have been set here. Pass the Brandenburg Gate and finish near the historic Reichstag building.',
        totalDistanceMeters: 42195,
        color: '#000000',
        difficulty: 'Hard',
        image: require('../../assets/berlin_marathon.png'),
        startCoordinate: { latitude: 52.5145, longitude: 13.3761 },
        endCoordinate: { latitude: 52.5163, longitude: 13.3777 },
        region: { latitude: 52.5200, longitude: 13.4050, latitudeDelta: 0.15, longitudeDelta: 0.15 },
        landmarks: [
            { id: 'ber-1', name: 'Straße des 17. Juni', distanceMeters: 0, description: 'Start near Brandenburg Gate' },
            { id: 'ber-2', name: 'Tiergarten', distanceMeters: 5000, description: 'Berlin\'s central park' },
            { id: 'ber-3', name: 'Potsdamer Platz', distanceMeters: 10000, description: 'Modern city center' },
            { id: 'ber-4', name: 'Kreuzberg', distanceMeters: 15000, description: 'Vibrant district' },
            { id: 'ber-5', name: 'Oberbaumbrücke', distanceMeters: 21098, description: 'Halfway - iconic bridge' },
            { id: 'ber-6', name: 'Friedrichshain', distanceMeters: 27000, description: 'East Berlin' },
            { id: 'ber-7', name: 'Alexanderplatz', distanceMeters: 33000, description: 'TV Tower view' },
            { id: 'ber-8', name: 'Unter den Linden', distanceMeters: 39000, description: 'Historic boulevard' },
            { id: 'ber-9', name: 'Brandenburg Gate', distanceMeters: 42195, description: 'Triumphant finish!' },
        ]
    },
];

// Combined for backward compatibility
export const TRAILS: Trail[] = [...INDIAN_TRAILS, ...CLASSIC_MARATHONS, ...CITY_MARATHONS];

